version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /var/apps/elaap-ui-v1
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
   - location: scripts/appstart.sh
     timeout: 120
     runas: ubuntu